### ISSUE TITLE
Vite Vue TS intellisense error: Argument of type 'ComputedRef<>' is not assignable to parameter of type 'ValidationArgs<>'

### ISSUE THREAD

**Issue by cindrmon** [vuelidate/vuelidate#1012]
**Describe the bug**
I'm trying out vuelidate 2 alpha with typescript and vite, and there seems to be an issue with the typescript linter complaining about the types `ComputedRef<{}>` and `ValidationArgs<{}>`. I was following the instructions provided in making vuelidate rules, and I don't know why there's an error with typescript regarding the manner. Is there some sort of thing that I should've done that I don't know about? Like some sort of typecasting?

**Reproduction URL**
I apologise if I wasn't able to use the provided codesandbox templates provided, since the issue is on vite and not on vue-cli. Provided [here](https://codesandbox.io/s/vite-vue-ts-vuelidate-sample-x3mek3) is the URL of the code. The issue cannot be seen through codesandbox, and it will only be visible if you check the typescript linting on vscode itself. The file and line in question is on `./src/components/FormComposition.vue` on ln 32.

**To Reproduce**
1. Create a new vite project using the terminal using the vue-ts template: `yarn create vite --template vue-ts vuelidate-issue-test`.
2. Open the project on VS Code.
3. Open the VS Code inbuilt terminal and run `yarn` to initialise the project.
4. Install `vuelidate/core` and `vuelidate/validators` onto the project: `yarn add @vuelidate/core @vuelidate/validators`.
5. Create a new vue file component called `Form.vue` in `src/components` folder.
6. Copy the code written below.
```vue
// Form.vue

<script lang="ts" setup>
import { useVuelidate } from "@vuelidate/core";
import { required, email, minLength, sameAs } from "@vuelidate/validators";
import { reactive, computed } from "vue";

const state = reactive({
  email: "",
  password: {
    pass: "",
    confirm: "",
  },
});

const rules = computed(() => {
  return {
    email: { required, email },
    password: {
      pass: { required, minLength: minLength(6) },
      confirm: { required, sameAs: sameAs(state.password.pass) },
    },
  };
});

// const rules = {
//   email: { required, email },
//   password: {
//     pass: { required, minLength: minLength(6) },
//     confirm: { required, sameAs: sameAs(state.password.pass) },
//   },
// };

const v$ = useVuelidate(rules, state);

const submitForm = () => {
  // vuelidate validation
  v$.value.$validate();

  // if success
  if (!v$.value.$error) {
    alert("Form Successfully Submitted!");
  }
  // // if fail
  // else {
  //   alert(
  //     "I'm sorry, you seem to not have filled all inputs. Please fill them up and try again."
  //   );
  // }
};
</script>

<template>
  <div class="root">
    <h2>Create an Account</h2>
    <p>
      <input type="text" v-model="state.email" placeholder="Email" />
      <span v-if="v$.email.$error">
        {{ v$.email.$errors[0].$message }}
      </span>
    </p>
    <p>
      <input
        type="password"
        v-model="state.password.pass"
        placeholder="Password"
      />
      <span v-if="v$.password.pass.$error">
        {{ v$.password.pass.$errors[0].$message }}
      </span>
    </p>
    <p>
      <input
        type="password"
        v-model="state.password.confirm"
        placeholder="Confirm Password"
      />
      <span v-if="v$.password.confirm.$error">
        {{ v$.password.confirm.$errors[0].$message }}
      </span>
    </p>
    <button @click="submitForm">Submit</button>
  </div>
</template>
```
7. Go back to the `App.vue` file, and update the file as is:
```diff
// App.vue

    <script setup lang="ts">
-    // This starter template is using Vue 3 <script setup> SFCs
-    // Check out https://v3.vuejs.org/api/sfc-script-setup.html#sfc-script-setup
-    import HelloWorld from './components/HelloWorld.vue'
+    import Form from './components/Form.vue'
    </script>
    
    <template>
-      <img alt="Vue logo" src="./assets/logo.png" />
-      <HelloWorld msg="Hello Vue 3 + TypeScript + Vite" />
+      <Form />
    </template>

    <style>
    #app {
      font-family: Avenir, Helvetica, Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      text-align: center;
      color: #2c3e50;
      margin-top: 60px;
    }
    </style>
```
8. Run the development server using `yarn dev`.

**Expected behavior**
There are no errors when running it in the development server, but the only issue is that the typescript linter is complaining about incompatible types.

**Screenshots**
![where the typescript error shows up](https://imgur.com/JXzrv9V.png)

**Additional context**
I was following a [tutorial by LearnVue](https://learnvue.co/2020/01/getting-smart-with-vue-form-validation-vuelidate-tutorial), and when I reached the section where [the tutorial is converting the code from the options api to the composition api](https://learnvue.co/2020/01/getting-smart-with-vue-form-validation-vuelidate-tutorial/#using-vuelidate-with-the-composition-api), and I stumbled upon on how to initialise the `useVuelidate()` method. When I tried doing it myself, the typescript lint `Argument of type 'ComputedRef<{email: required...}>' is not assignable to parameter of type 'ValidationArgs<{email: string;...}>'.

**Comment by rathax** [comment]
I have a similar issue since yesterday, after upgrading to 2.0.0-alpha.35. 

`
Argument of type '{ password: { required: ValidationRuleWithoutParams<any>; }; }' is not assignable to parameter of type 'ValidationArgs<{ password: Ref<string>; }> | Ref<ValidationArgs<{ password: Ref<string>; }>>'.
  Type '{ password: { required: ValidationRuleWithoutParams<any>; }; }' is not assignable to type 'ValidationArgs<{ password: Ref<string>; }>'.ts(2345)
`

**Comment by dobromir-hristov** [comment]
I could use some TS help here. I am not sure how to fix this one.

**Comment by mat813** [comment]
Ok, so, it seems the type inference is a bit too strict. Here is what I had before :

```typescript
const rules = {
     bitstream_trunk: {},
     extra_information: {},
     offers_uniqids: { required },
     customer_name: { required },
     pe_configuration: {},
     premises_availability_date: {},
     webhook_url: {},
   };

 const orderv$ = useVuelidate(rules, newOrder);
```

and here is what I need to have now for it to be valid, but it is simply telling typescript that it should ignore what I actually have and go with it:

```typescript
const rules = {
     bitstream_trunk: {} as ValidationRule<string | undefined>,
     extra_information: {} as ValidationRule<string | undefined>,
     offers_uniqids: { required } as unknown as ValidationRule<string>,
     customer_name: { required } as unknown as ValidationRule<string>,
     pe_configuration: {} as ValidationRule<'router' | 'bridge' | undefined>,
     premises_availability_date: {} as ValidationRule<string>,
     webhook_url: {} as ValidationRule<string | undefined>,
   };

 const orderv$ = useVuelidate(rules, newOrder);
```

I also could keep the rules I have and write:

```typescript
 const orderv$ = useVuelidate(rules as any, newOrder);
```

**Comment by schw4rzlicht** [comment]
I can confirm the same issue for vue-cli ~5.0.1. `@vuelidate/core@2.0.0-alpha.34` is working.

**Comment by dobromir-hristov** [comment]
Is this something that got introduced with the latest release? We had a PR contribution with some changes to the types

**Comment by schw4rzlicht** [comment]
Apparently yes. For me it only happens after upgrading to `2.0.0-alpha.35`, the same as for @rathax.

**Comment by dobromir-hristov** [comment]
Great... Can any of you check that PR and if we can't figure it out, we revert

**Comment by cindrmon** [comment]
Yea, I think you're right! I just reverted to `2.0.0-alpha.34`, and the error disappeared. Looks like there was some sort of difference between alpha 34 and alpha 35 with regarding that error. Kudos to you for finding that out.

> Apparently yes. For me it only happens after upgrading to `2.0.0-alpha.35`, the same as for @rathax.

**Comment by cindrmon** [comment]
>
> I also could keep the rules I have and write:
> 
> ```ts
>  const orderv$ = useVuelidate(rules as any, newOrder);
> ```

Also, it gave me additional errors when i set `rules as any`:

![https://imgur.com/AAiFzrR.png](https://imgur.com/AAiFzrR.png)

**Comment by cindrmon** [comment]
Does this mean, I should not use the latest alpha for this to not happen? Or do I have to change how I make my rules? Because, this is how i coded my rules, as per the instructions by LearnVue:

```vue
<script lang="ts" setup>
import { useVuelidate } from "@vuelidate/core";
import { required, email, minLength, sameAs } from "@vuelidate/validators";
import { reactive, computed } from "vue";

...

const rules = computed(() => {
  return {
    email: { required, email },
    password: {
      pass: { required, minLength: minLength(6) },
      confirm: { required, sameAs: sameAs(state.password.pass) },
    },
  };
});
</script>
```

> and here is what I need to have now for it to be valid, but it is simply telling typescript that it should ignore what I actually have and go with it:
> 
> ```ts
> const rules = {
>      bitstream_trunk: {} as ValidationRule<string | undefined>,
>      extra_information: {} as ValidationRule<string | undefined>,
>      offers_uniqids: { required } as unknown as ValidationRule<string>,
>      customer_name: { required } as unknown as ValidationRule<string>,
>      pe_configuration: {} as ValidationRule<'router' | 'bridge' | undefined>,
>      premises_availability_date: {} as ValidationRule<string>,
>      webhook_url: {} as ValidationRule<string | undefined>,
>    };
> 
>  const orderv$ = useVuelidate(rules, newOrder);
> ```
> 

Also, i couldn't really find an equivalent `ValidationRule` for `email`, `sameAs`, and `minLength`. I don't even know which docs to look for for doing those specific things as what you did.

Anyways, thanks for the feedback. I didn't know I'm not just alone here having the same problem with typescript.

**Comment by Kolobok12309** [comment]
We write some helper above `vuelidate@next` and use this interface
```ts
export type ValidationArgs<T = unknown> = {
  [key in keyof T]: T[key] extends Record<string, unknown>
    ? ValidationArgs<T[key]>
    : Record<string, ValidationRule<T[key]>>
}
```

Actual realization is wrong and approve this code
```ts
// Current
useVuelidate({
  password: required,
  passwordConfirmation: required,
}, {
  password: '',
  passwordConfirmation: '',
});

// What expected by doc
useVuelidate({
  password: {
    required,
  },
  passwordConfirmation: {
    required,
  },
}, {
  password: '',
  passwordConfirmation: '',
});
```
https://github.com/vuelidate/vuelidate/blob/a9eb302e668c5514500edda9a96857410e3332e9/packages/vuelidate/index.d.ts#L60-L62

**Comment by jaunt** [comment]
Same problem here.  I was able to get rid of the error for now with the following (even though I'm sure it's a bad hack and I'll change it as soon as there's a better fix):

```typescript
const state = ref({
  email: "",
  password: "",
});

const rules = computed(() => ({
  email: {
    required,
    email,
  },
  password: {
    required,
  },
}));

const v$ = useVuelidate(
  rules as unknown as ValidationArgs<{ email: string; password: string }>,
  state
);
```

**Comment by cindrmon** [comment]
> Same problem here. I was able to get rid of the error for now with the following (even though I'm sure it's a bad hack and I'll change it as soon as there's a better fix):
> 
> ```ts
> const state = ref({
>   email: "",
>   password: "",
> });
> 
> const rules = computed(() => ({
>   email: {
>     required,
>     email,
>   },
>   password: {
>     required,
>   },
> }));
> 
> const v$ = useVuelidate(
>   rules as unknown as ValidationArgs<{ email: string; password: string }>,
>   state
> );
> ```

i really do hope that they have made a better fix for this though

**Comment by RollingTL** [comment]
> Is this something that got introduced with the latest release? We had a PR contribution with some changes to the types

yes I have same problem. But after last update to 35 I find that another error is gone:
https://github.com/vuelidate/vuelidate/issues/983
Unfortunately I don't know my previous version number.

**Comment by cindrmon** [comment]
> > Is this something that got introduced with the latest release? We had a PR contribution with some changes to the types
> 
> yes I have same problem. But after last update to 35 I find that another error is gone: #983 Unfortunately I don't know my previous version number.


check your `package.json`, or check the npm website to see what you have installed. you might typically get the `latest` install.

**Comment by RollingTL** [comment]
> > > Is this something that got introduced with the latest release? We had a PR contribution with some changes to the types
> > 
> > 
> > yes I have same problem. But after last update to 35 I find that another error is gone: #983 Unfortunately I don't know my previous version number.
> 
> check your `package.json`, or check the npm website to see what you have installed. you might typically get the `latest` install.


I think it is impossible, as I simply had done 'npm update' today, and about 2-3 weeks before I also did 'npm update' and I did it many times approximately once per two-tree weeks for about a year.

**Comment by A-Ghorab** [comment]
i was checking the issues and i believe that #1022 will fix this one as well

so if you guys can check the code it's basically changing the ValidationArgs to this
 
```ts
export type ValidationArgs<T = unknown> = {
  [key in keyof T]?: ValidationArgs<T[key]> | ValidationRuleCollection<typeof T[key]> | ValidationRule<typeof T[key]>
}
```

**Comment by dobromir-hristov** [comment]
Going to close for now. If ppl still have issues with latest version will reopen

**Comment by mat813** [comment]
Ok, so, with v40, the issue moved a bit, I don't quite get how to make it work.

```ts
  type NewOrder = {
    bitstream_trunk?: string;
    extra_information?: string;
    offers_uniqids: string;
    customer_name: string;
    pe_configuration?: "router" | "bridge";
    webhook_url?: string;
    premises_availability_date: string;
  }

  const newOrder = reactive<NewOrder>({
    bitstream_trunk: '',
    extra_information: '',
    offers_uniqids: props.offerId,
    customer_name: '',
    pe_configuration: 'router',
    premises_availability_date: '',
    webhook_url: '',
  });

  const rules = {
    bitstream_trunk: {},
    extra_information: {},
    offers_uniqids: { required },
    customer_name: { required },
    pe_configuration: {},
    premises_availability_date: {},
    webhook_url: {},
  };

  const orderv$ = useVuelidate(rules, newOrder);
```

This gives me:

```
TS2345: Argument of type '{ bitstream_trunk?: string | undefined; extra_information?: string | undefined; offers_uniqids: string; customer_name: string; pe_configuration?: "router" | "bridge" | undefined; webhook_url?: string | undefined; premises_availability_date: string; }' is not assignable to parameter of type '{ bitstream_trunk: any; extra_information: any; offers_uniqids: any; customer_name: any; pe_configuration: any; premises_availability_date: any; webhook_url: any; } | Ref<{ bitstream_trunk: any; ... 5 more ...; webhook_url: any; }> | ToRefs<...>'.
  Type '{ bitstream_trunk?: string | undefined; extra_information?: string | undefined; offers_uniqids: string; customer_name: string; pe_configuration?: "router" | "bridge" | undefined; webhook_url?: string | undefined; premises_availability_date: string; }' is not assignable to type 'ToRefs<{ bitstream_trunk: any; extra_information: any; offers_uniqids: any; customer_name: any; pe_configuration: any; premises_availability_date: any; webhook_url: any; }>'.
    Types of property 'bitstream_trunk' are incompatible.
      Type 'string | undefined' is not assignable to type 'Ref<any>'.
        Type 'undefined' is not assignable to type 'Ref<any>'.
    781 |   }));
    782 |
  > 783 |   const orderv$ = useVuelidate(rules, newOrder);
        |                                       ^^^^^^^^
    784 |
```

I tried making the rules a computed property, but it does not change anything.

If I write:

```ts
  const orderv$ = useVuelidate<NewOrder>(rules, newOrder);
```

Then I get an error somewhere else:

```
TS2339: Property 'customer_name' does not exist on type 'Validation<ValidationArgs<unknown>, NewOrder>'.
    885 |           orderFns.orderv$.value.$touch();
    886 |
  > 887 |           if (orderFns.orderv$.value.customer_name.$error) {
        |                                      ^^^^^^^^^^^^^
    888 |             return 'Le nom du client doit être renseigné';
    889 |           }
    890 |
```

If I continue forcing types to useVuelidate:

```ts
  const orderv$ = useVuelidate<NewOrder, typeof rules>(rules, newOrder);
```

Then I get another error:

```
TS2344: Type 'NewOrder' does not satisfy the constraint '{ bitstream_trunk: any; extra_information: any; offers_uniqids: any; customer_name: any; pe_configuration: any; premises_availability_date: any; webhook_url: any; }'.
  Property 'bitstream_trunk' is optional in type 'NewOrder' but required in type '{ bitstream_trunk: any; extra_information: any; offers_uniqids: any; customer_name: any; pe_configuration: any; premises_availability_date: any; webhook_url: any; }'.
    781 |   };
    782 |
  > 783 |   const orderv$ = useVuelidate<NewOrder, typeof rules>(rules, newOrder);
        |                                ^^^^^^^^
    784 |
```

If I remove the empty rules, like this:

```ts
  const rules = {
    offers_uniqids: { required },
    customer_name: { required },
  };

  const orderv$ = useVuelidate<NewOrder, typeof rules>(rules, newOrder);
```

I don't get errors any more, but, the properties don't exist any more on the validation object and I can't call `orderv$.extra_information.$model` without getting an error.

**Comment by A-Ghorab** [comment]
just an idea can you make it 

```ts
  const newOrder = reactive({
    bitstream_trunk: '',
    extra_information: '',
    offers_uniqids: props.offerId,
    customer_name: '',
    pe_configuration: 'router',
    premises_availability_date: '',
    webhook_url: '',
  });

  const rules = {
    bitstream_trunk: {},
    extra_information: {},
    offers_uniqids: { required },
    customer_name: { required },
    pe_configuration: {},
    premises_availability_date: {},
    webhook_url: {},
  };

  const orderv$ = useVuelidate(rules, newOrder);

```

by removing the definition of type "NewOrder" from reactive would the error still exist?

**Comment by mat813** [comment]
I had not tried that, but If I remove the type, I cannot use newOrder afterwards because its type is not compatible with the object I want to create/update:

```
TS2322: Type '{ installation_site_contact_id: string; technical_contact_id: string; billing_contact_id: string; premises_availability_date: number; bitstream_trunk: string; extra_information: string; offers_uniqids: string; customer_name: string; pe_configuration: string; webhook_url: string; }' is not assignable to type 'OrderCreate'.
  Types of property 'pe_configuration' are incompatible.
    Type 'string' is not assignable to type '"router" | "bridge" | undefined'.
    786 |     const client = await publicClient;
    787 |
  > 788 |     const orderSubmit: Components.Schemas.OrderCreate = {
        |           ^^^^^^^^^^^
    789 |       ...newOrder,
```

**Comment by A-Ghorab** [comment]
ok i see the whole picture now 

i believe it's related undefined types like bitstream_truck

so just remove them as you already assigning them value

```ts
type NewOrder = {
    bitstream_trunk: string;
    extra_information: string;
    offers_uniqids: string;
    customer_name: string;
    pe_configuration: "router" | "bridge";
    webhook_url: string;
    premises_availability_date: string;
  }
```

i will do more testing on this undefined scenario maybe  i can provide a definition that bypass the error for you

**Comment by mat813** [comment]
Using `Required<NewOrder>` as the type for the `reactive` call works. (It is a compound type, so I can't just change its definition.) It does feel strange to have to have all fields be required, when they are not really. It would be great if vuelidate types could accept types with optional fields.
